### PR TITLE
when init with array of JSON( [JSON] ), set according rawArray

### PR DESCRIPTION
**Pull request by flybrotherlixiang**

### CODE REVIEW

**Comment by ldiqual** [comment]
@flybrotherlixiang Thanks for your contribution! Would you mind elaborating on what this fixes?

**Comment by wongzigii** [comment]
Hello @flybrotherlixiang .Thanks for your PR so much! I would like to merge this into master. Could you help out to fix some format, which it should use 4 spaces indentation instead.

**Comment by flybrotherlixiang** [comment]
@wongzigii

**Comment by wongzigii** [comment]
Sorry for the late response. @flybrotherlixiang Looks like `rawArray` is being set correctly now, so I am going to close this issue. https://github.com/SwiftyJSON/SwiftyJSON/blob/master/Source/SwiftyJSON.swift#L225

**Pull request closed without merging**
