### PR TITLE
Create devcontainer.json

### PR DESCRIPTION
**Pull request by Bankrollshow**
The PR should summarize what was changed and why. Here are some questions to
help you if you're not sure:

 - What behavior was changed?
 - What code was refactored / updated to support this change?
 - What issues are related to this PR? Or why was this change introduced?

Checklist - While not every PR needs it, new features should consider this list:

 - [x] Does this have tests?
 - [x] Does this have documentation?
 - [x] Does this break the public API (Requires major version bump)?
 - [x] Is this a new feature (Requires minor version bump)?

### CODE REVIEW

**Review by Bankrollshow — COMMENTED** [review]
update

**Review by Bankrollshow — COMMENTED** [review]
[]()

**Review by Bankrollshow — COMMENTED** [review]
Update

**Comment by wongzigii** [comment]
Hi @Bankrollshow  What's this file for?

**Comment by Adobels** [comment]
@wongzigii devcontainer.json file is a Visual Studio Code configuration for Microsoft's "Dev Container" Extension, which allows configuring and launching Docker Images. When working with SwiftyJSON on macOS and needing to simulate the Linux platform, it is interesting to use it to speed up setting up an environment.

The PR includes such a configuration file, but the problem is that the proposed container is only available on Windows platforms and is not accessible on macOS. The solution would be to propose a container provided by the Swift Developer Community or one from Ubuntu.

Anyway, there are other IDEs for Linux development, and developers who work on this platform usually have their workflows and tooling chains.

This PR can be closed due to the container not being multiplatform and causing errors when deploying it on macOS.

**Comment by wongzigii** [comment]
> @wongzigii devcontainer.json file is a Visual Studio Code configuration for Microsoft's "Dev Container" Extension, which allows configuring and launching Docker Images. When working with SwiftyJSON on macOS and needing to simulate the Linux platform, it is interesting to use it to speed up setting up an environment.
> 
> The PR includes such a configuration file, but the problem is that the proposed container is only available on Windows platforms and is not accessible on macOS. The solution would be to propose a container provided by the Swift Developer Community or one from Ubuntu.
> 
> Anyway, there are other IDEs for Linux development, and developers who work on this platform usually have their workflows and tooling chains.
> 
> This PR can be closed due to the container not being multiplatform and causing errors when deploying it on macOS.

Thanks for the clarification. 👍

**Pull request closed without merging**
