### PR TITLE
Xcode7

### PR DESCRIPTION
**Pull request by qq251569880**

### CODE REVIEW

**Comment by leversol** [comment]
Please fix that:  'stringByAddingPercentEscapesUsingEncoding' is deprecated: Use stringByAddingPercentEncodingWithAllowedCharacters(_:) instead
See ligne 888
Xcode 7 b5

**Comment by maartenschumacher** [comment]
Tried to build it with carthage, but got this error: `target 'SwiftyJSON watchOS' has bitcode disabled (ENABLE_BITCODE = NO), but it is required for the 'watchos' platform` Help?

**Comment by bcapps** [comment]
@tangplin Should this be merged into master (with a new Cocoapods version) now that Xcode 7 GM is out?

**Comment by Danappelxx** [comment]
Please do so - I'm can't add swiftyjson as a dependency in my pod spec before you do.

**Comment by devxoul** [comment]
I think it's time to merge Xcode 7 branch in master. Alternatively you guys can consider using [CocoaSeeds](https://github.com/dvxoul/CocoaSeeds) to specify branch.

**Pull request merged**
