### PR TITLE
Basic playground set.

### PR DESCRIPTION
**Pull request by JeffGuKang**
Playground for anybody who want to play with SwiftyJSON.

### CODE REVIEW

**Comment by zhigang1992** [comment]
Awesome, looks good. This is definitely a good start on utilizing the playground.

I actually have a bit more ambition on this, making it a living document for the actual code.
If you are interested: 

Like code examples in the README file, we can porting it over to this playground.

What do you think?

**Comment by JeffGuKang** [comment]
Making a live document will be fun feature. 
Then, how about using [MarkUp] (https://developer.apple.com/library/content/documentation/Xcode/Reference/xcode_markup_formatting_ref/index.html#//apple_ref/doc/uid/TP40016497) for the playground when do porting the examples from `README`?

**Comment by zhigang1992** [comment]
@JeffGuKang definitely, let's do it. 😄

**Comment by JeffGuKang** [comment]
Cool. 👍

**Comment by JeffGuKang** [comment]
I will update TODO list.

**Comment by zhigang1992** [comment]
LGTM 👍

**Pull request merged**
