### PR TITLE
Fix incompatibility with Carthage

### PR DESCRIPTION
**Pull request by Thomvis**
Carthage tries to build the framework targets in the first project it finds. It finds `Example.xcodeproj` first, so no frameworks are built, or at least not all the time. See https://github.com/Carthage/Carthage/issues/532.

This PR moves the example project into a subdirectory and makes SwiftyJSON work with Carthage again.

### CODE REVIEW

**Comment by adly-holler** [comment]
+1

**Comment by Pym** [comment]
:+1:

**Comment by valeIT** [comment]
+1

**Comment by wakinchan** [comment]
+1

**Comment by xiongcaixing1986** [comment]
+1

**Comment by kylejm** [comment]
When can we expect this to be merged?

**Comment by schickling** [comment]
+1

**Comment by bachirelkhoury** [comment]
is this going to be merged soon? been almost a month. 
thanks

**Comment by jarrodrobins** [comment]
+1

**Comment by schickling** [comment]
@tangplin is there anything missing?

**Comment by freennnn** [comment]
+1

**Comment by parkej60** [comment]
+1

**Comment by devnevins** [comment]
+1. Found the same issue. A workaround is to delete **Example.xcodeproj** in the Carthage/Checkouts/SwiftyJSON directory. Once deleted move to your project directory and issue the **carthage build** command rather than the **carthage update** command. If you reissue carthage update you'll have the same problem.

**Comment by morizotter** [comment]
+1

**Comment by rhydiant** [comment]
+1

**Comment by algal** [comment]
+1

**Comment by Spencevail** [comment]
Kind of annoying that this is still an issue...

**Comment by jarrodrobins** [comment]
Yeah. Any chance of a merge, @tangplin? Pleeeeease?

**Comment by j1881** [comment]
+1

**Comment by narfdotpl** [comment]
@tangplin fixed this in 4cf6f023d4023848914b6e35baa655d278f34ef6. :sparkles: Thanks! :+1: 

@Thomvis, I think you can close this pull request. :closed_book:

**Pull request closed without merging**
