### PR TITLE
String keypath support 

### PR DESCRIPTION
**Pull request by vasilyIvanov**
JSON objects can be indexed by a key path like "items.0.isActive"

### CODE REVIEW

**Comment by zhigang1992** [comment]
Nice work.

One concern that I have is that this might break other ppl's existing app.
Also, how would you differentiate index 0 and string `"0"`?

Also, apologize for not getting to this PR earlier.

**Comment by vasilyIvanov** [comment]
Hi

how it can break existing apps? This branch is just adding support for key paths, old functionality is working as earlier. Can you please come up with breaking test case?

Yes, it's impossible to tell 0 and "0" at the moment. Those who want to use keys like "0" would have to stick to the old plain comma-separated paths. I guess it's not a big deal since it wouldn't crash anything, just failure.

When I were creating this PR my concern were to support key paths as it's already have been done in Apple frameworks so people wouldn't frustrate when moving to SwiftyJSON.

**Comment by zhigang1992** [comment]
Hm, for instance, if someone out there is using . in their json key. (I know it's not quiet possible)
Like:

{"com.apple.app1":"fadbifdoafboadbfojabdfoajbfhauebbfuuryrwowrgk"}

Then this pr will cause their code to fail, and their is no way for them to easily fix it.

Granted, same thing happens for valueForKeyPath, still a bit of concern from my point of view.

What do you think?

**Comment by vasilyIvanov** [comment]
Yes, agreed. On reading we can first try to read `com.apple.app1` and then `com`, `apple`, `app1`, but for writing I can't think of any decent logic.
Sorry for bothering, let's abandon this PR.

**Comment by zhigang1992** [comment]
Feel free to reopen this if needed.

Cheers

**Pull request closed without merging**
