### PR TITLE
Swift3 gm updates

### PR DESCRIPTION
**Pull request by jeneumeier**
Source, tests, and example updated to Swift 3.0 GM.

### CODE REVIEW

**Comment by dantaylorseo** [comment]
I can confirm that this compiles and works as expected in Xcode 8 with iOS 10.0.1

**Comment by lukas2** [comment]
I think the initializer signature should look like this:

`public init(data:Data, options opt: JSONSerialization.ReadingOptions = .allowFragments, error: NSErrorPointer = nil) `

The reason is that NSErrorPointer is defined as Optional in Swift 3:

`public typealias NSErrorPointer = AutoreleasingUnsafeMutablePointer<NSError?>?`

**Comment by calvinlyc** [comment]
Any update for this PR and do you know when it will be merged in? Thanks :)

**Comment by zhigang1992** [comment]
👍  LGTM, will merge now. sry for the late response.

**Comment by DenHeadless** [comment]
Thanks, are you going to make a release on CocoaPods?

**Comment by zhigang1992** [comment]
@DenHeadless yeap, will be done in a bit.

**Comment by zhigang1992** [comment]
@DenHeadless it's done, version 3.0.0 is now in CocoaPods

**Comment by DenHeadless** [comment]
Thank you so much!

**Comment by lukas2** [comment]
@zhigang1992 :
Thank you for merging this. 👍 

Please consider, as a follow-up, also merging #641 . See my comment above.

**Pull request merged**
