### PR TITLE
Adds Support for Nested JSON

### PR DESCRIPTION
**Pull request by hectormatos2011**
Currently, getting rawdata from JSON objects fails and breaks when nesting other JSON objects together. This PR fixes that and adds tests for the test cases where this can fail.

### CODE REVIEW

**Comment by hectormatos2011** [comment]
The reasoning behind this PR is because currently, in order to nest JSON objects, we need to do something like this:

```swift
let example: JSON = [
    "hello" : "there"
]

let nested: JSON = [
    "whats" : "up"
    "example" : example.object
]
```

For developers migrating to SwiftyJSON from using dictionaries before, it's not immediately apparent that this case crashes when getting rawData from the `nested` object because `JSONSerialization` doesn't recognize the `JSON` struct as serializable. Plus, a developer would expect to be able to construct JSON objects like this fairly regularly. Especially when developers start moving to Swift on the backend.

Merging this PR would allow a developer to do this:

```swift
let example: JSON = [
    "hello" : "there"
]

let nested: JSON = [
    "whats" : "up"
    "example" : example
]
```

**Comment by hectormatos2011** [comment]
The last commit I put in was a direct duplicate of #589. The reasoning for this is because my changes will directly conflict with those changes. This brings in the performance enhancements while still supported nested JSON.

**Comment by hectormatos2011** [comment]
This is weird. Tests are passing on my machine.

**Comment by hectormatos2011** [comment]
Could we restart travis?

**Comment by nicholas-lonsinger** [comment]
I forked this and it succeeded twice in Travis. From looking on the web, this could be related to many things, but the intermittent nature of it lends itself to being a timeout issue which many people believe to be the cause.

There is a "Restart Build" button in travis, so if this error comes back you could always try that. Otherwise there are numerous suggestions on how to mitigate or work around this issue, but it's hard to see if they help if the issue is not currently happening.

**Comment by hectormatos2011** [comment]
@nicholas-lonsinger Thanks for that. I think because I don't have access, I can't restart the build myself. I tried looking and couldn't find the restart build button that's normally there.

**Comment by zhigang1992** [comment]
LGTM 👍

**Comment by penacristian** [comment]
I am trying to parse a JSON object (dictionary). When I access a value for key, I don't get another JSON, I get a [String: JSON]. Is there a way to treat a JSON dictionary object as a [string: JSON] and keep parsing recursively?

**Pull request merged**
