### PR TITLE
Update for Swift 1.2

### PR DESCRIPTION
**Pull request by justinmakaila**

### CODE REVIEW

**Comment by justinmakaila** [comment]
Hmm... build completes on my machine but not Travis. Looking into it now.

**Comment by rcgary** [comment]
@justinmakaila Please check on the `xcode6.3` brunch.

**Comment by justinmakaila** [comment]
:+1:

**Comment by tangplin** [comment]
Done db2b0274684779ee0d6e0f169f89f499883260a0

**Pull request closed without merging**
