### PR TITLE
migrate swift 3 Xcode 8

### PR DESCRIPTION
**Pull request by AnYuan**
wish to help.

### CODE REVIEW

**Comment by simonnarang** [comment]
I

**Comment by AnYuan** [comment]
@simonnarang you're welcome😃

**Comment by piyushwadhwani** [comment]
please merge this into swift3 branch

**Comment by leejaedus** [comment]
please merge this into swift3 branch

**Comment by mylonly** [comment]
please merge this into swift3 branch, I need it

**Comment by gaming-hacker** [comment]
learn git and pull it into your own repo

**Comment by simonnarang** [comment]
It's not that hard, just get rid of the colon stuff in the json extension

**Comment by piyushwadhwani** [comment]
its not about just removing its about merging it in swift3

**Comment by AnYuan** [comment]
update under Xcode 8 beta4, and pass all the tests.

**Comment by AnYuan** [comment]
update under Xcode 8 beta6, and pass all the tests.

**Comment by funkenstrahlen** [comment]
please merge

**Comment by sureshsubbaiah** [comment]
please merge this into swift3 branch..

**Comment by valheru7** [comment]
someone going to merge this?

**Comment by arronhunt** [comment]
Bump for a merge?

**Comment by pcantrell** [comment]
Tested this PR in an actual project. Confirmed that it compiles and it appears to work just fine.

**Comment by AnYuan** [comment]
@arronhunt [here](https://github.com/BaiduHiDeviOS/SwiftyJSON/tree/swift3) is my fork repo.

**Comment by esetnik** [comment]
@AnYuan can you add the `s.pod_target_xcconfig = { 'SWIFT_VERSION' => '3.0' }` to your podfile for compatibility with Cocoapods

**Comment by AnYuan** [comment]
@esetnik already merged your pull request to my repo, thanks.

**Comment by zhigang1992** [comment]
Thank you for sending this PR, and apologize for not getting to this sooner.

Anyway, we have landing swift3 support in master branch. 

Feel free to give it a go.

🍻

**Pull request closed without merging**
