### PR TITLE
Fix all Xcode 8.1 compilation warnings

### PR DESCRIPTION
**Pull request by ldiqual**
@zhigang1992 Please review

Fixes https://github.com/SwiftyJSON/SwiftyJSON/issues/703

Pretty straightforward, let me know if you have any question

### CODE REVIEW

**Comment by wongzigii** [comment]
FYI: Sometimes CI is broken for this known issue: https://github.com/travis-ci/travis-ci/issues/6675

**Comment by ldiqual** [comment]
@wongzigii Restarted the build and tests passed correctly. Can you review this PR as well, I'll take which ever 👍 comes first :P

**Comment by wongzigii** [comment]
LGTM

**Comment by zhigang1992** [comment]
👍

**Pull request merged**
