### PR TITLE
Syntax updates and fixes for Swift 3.0 and Xcode 8 beta 6

### PR DESCRIPTION
**Pull request by druidsbane**
Hi,

Changes for Swift 3.0 and Xcode 8 beta 6.  Hope this helps.

Thanks!

### CODE REVIEW

**Comment by druidsbane** [comment]
Only tests failing now are for subscripts. Assignment once an array or dictionary is created doesn't work though initial creation is fine. All other tests work.

**Comment by bre7** [comment]
Private vars should be fileprivate

**Comment by zhigang1992** [comment]
Thank you for sending this PR.

I know you send this first, but I started merge from the top. lol

Anyway, we have landing swift3 support in master branch. 

Feel free to give it a go.

🍻

**Comment by druidsbane** [comment]
Thanks! Will check out.

**Pull request closed without merging**
