### PR TITLE
Support for Swift 2

### PR DESCRIPTION
**Pull request by andrelind**
Converted SwiftyJSON to Swift2 syntax and fixed all warnings

### CODE REVIEW

**Comment by kamoljan** [comment]
+1

**Comment by mathiasnagler** [comment]
+1

**Comment by duemunk** [comment]
+1

**Comment by ryanschneider** [comment]
+1 (for this being manually merged into a new swift-2.0 branch, not accepted on master until XCode 7 is at least in public beta).

**Comment by lingoer** [comment]
Great job!
Since XCode7 and Swift2 is still in beta I'm considering branching the repo to support Swift1 and 2 separately. What do you think?

**Comment by kamoljan** [comment]
@lingoer +1 please do this!

**Comment by duemunk** [comment]
@lingoer Most just use the swift-2.0 branch and works just fine.

**Comment by dduan** [comment]
@lingoer +1 for @duemunk's branching model. Keep swift-2.0 compatible version on a `swift-2.0` branch until Xcode 7 is out of beta. In addition, please consider:

1. switch the default branch on Github to `swift-2.0` (to affirm Swift-2.0 readiness and make it easier to discover).
2. tag a new release on `swift-2.0` (for Carthage users).

**Comment by JackieQi** [comment]
+1 @dduan

**Comment by RuiAAPeres** [comment]
Any update on this? cc @tangplin

**Comment by JackieQi** [comment]
@RuiAAPeres There is a "Xcode7" branch which fixed the issue.

**Comment by RuiAAPeres** [comment]
@JackieQi tried it and it didn't work.

**Comment by ded** [comment]
What's the status on this PR?

**Comment by ricardogobbo** [comment]
+1!

**Comment by rockia** [comment]
+1 I would really love to see the stable branch for Swift 2.0 releasing.

**Comment by patrickreynolds** [comment]
Is there any update on this yet?

**Comment by Danappelxx** [comment]
Bah I've been waiting for a week now can you please just merge the branches 😓

**Comment by iamjason** [comment]
@ricardogobbo  I was able to use CocoaPods by targeting the XCode 7 branch like this:

``` pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git', :branch => 'xcode7' ```

**Comment by Danappelxx** [comment]
@iamjason that works in your podfile, but you can't add it as a dependency in your podspec.

**Comment by leegoodrich** [comment]
iOS 9 and XCode 7 are now out of beta and are the latest public stable releases. Is there any update here? SwiftyJSON is now broken for anyone downloading the latest stable XCode release.

**Comment by vbrazo** [comment]
+1

**Comment by scibidoo** [comment]
Make it so... please

**Comment by Jleaton** [comment]
Any status update on this?

**Comment by alexdd55** [comment]
+1

**Comment by owingst** [comment]
Got an email saying this issue was closed....but nothing here that says so....whats up?

**Comment by Danappelxx** [comment]
@owingst Swift 2 support is already in the master branch :)

**Comment by owingst** [comment]
That is great. Thanks!

**Pull request closed without merging**
