### PR TITLE
[WIP]  swift test in Linux

### PR DESCRIPTION
**Pull request by wongzigii**
**WIP**

Fixs https://github.com/SwiftyJSON/SwiftyJSON/pull/708

This PR aims at porting SwiftyJSON to Linux Platform.

### CODE REVIEW

**Comment by ldiqual** [comment]
@wongzigii Can you clarify what's left on this PR? Do you need an extra hand maybe?

**Comment by wongzigii** [comment]
@ldiqual SPM currently doesn't provide a way to include resources e.g. `.json` file to be tested.

Relate: 

https://lists.swift.org/pipermail/swift-users/Week-of-Mon-20161114/003987.html
https://lists.swift.org/pipermail/swift-users/Week-of-Mon-20161107/003912.html

**Comment by ldiqual** [comment]
@wongzigii Given that it will remain unfixed for a while, maybe we should go ahead and put the test in a [gist](https://gist.github.com/) that we'd download during the test? In theory it shouldn't be too hard to implement, it'd just make one test case a tad slow. What do you think?

**Comment by wongzigii** [comment]
It makes sense at this time as a workaround. I will give it a try later.

**Comment by wongzigii** [comment]
Closing in favor of #943

**Pull request closed without merging**
