### PR TITLE
Change ++ to Swift 3 compatible += 1

### LINKED ISSUE #455: '++' is deprecated: it will be removed in Swift 3
The following code triggers this warning when building with Swift 3:

``` swift
    public mutating func next() -> JSONGenerator.Element? {
        switch self.type {
        case .Array:
            if let o = self.arrayGenerate!.next() {
                return (String(self.arrayIndex++), JSON(o)) // *** This is the line with the warning
            } else {
                return nil
            }
        case .Dictionary:
            if let (k, v): (String, AnyObject) = self.dictionayGenerate!.next() {
                return (k, JSON(v))
            } else {
                return nil
            }
        default:
            return nil
        }
    }
```

### PR DESCRIPTION
**Pull request by natebird**
This closes #455.

### CODE REVIEW

**Comment by natebird** [comment]
Looking into why the change is failing. Sorry.

**Comment by natebird** [comment]
The intent of returning the current index in now clearer but it’s a couple more lines of code and it’s doing multiple things. I can’t think of a better way of refactoring it since the method. Any other ideas?

**Comment by natebird** [comment]
I see that this has been changed in the master branch now. I’ll close this pull request.

**Comment by racer1988** [comment]
I still get this warning 
SwiftyJSON/Source/SwiftyJSON.swift:399:47: warning: '++' is deprecated: it will be removed in Swift 3

on cartage (last version available is 2.3.3)

When is a new version planned?

**Pull request closed without merging**
